In [1]:
import os
import numpy as np 
import pandas as pd

In [2]:
X_train = pd.read_csv("data/ancestry_train.data", sep = " ", header=None).values
y_train = pd.read_csv("data/ancestry_train.solution", sep = " ", header=None).values

X_test = pd.read_csv("data/ancestry_test.data", sep = " ", header=None).values

In [3]:
X_train

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [4]:
np.round(y_train, 3)

array([[0.198, 0.75 , 0.052],
       [0.858, 0.142, 0.   ],
       [0.761, 0.237, 0.001],
       ...,
       [0.001, 0.183, 0.817],
       [0.016, 0.591, 0.393],
       [0.   , 0.007, 0.993]])

In [5]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 2, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 1, 1],
       [0, 0, 2, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

# cost function

In [6]:
def cost(y_true, y_hat):
    mse = -np.log10(np.mean((y_true-y_hat)**2)+1e-5)
    return(mse)

# baseline

In [7]:
base = np.ones((y_train.shape[0], y_train.shape[1])) * (1/3)
cost(y_train, base)

0.8401067369385945

In [8]:
y_test = np.ones((X_test.shape[0], y_train.shape[1])) * (1/3)

# save and zip the file

In [9]:
pd.DataFrame(y_test).to_csv(f"predictions.csv", sep = " ", header = None, index = None)
os.system("zip -r predictions.zip predictions.csv")

updating: predictions.csv (deflated 100%)


0